// Planning input for the 8 September activity breakdown. No external actions.
const newTasks = [
  [151, 'Specify foundation learning pathway contracts', 'P01', 'SP-007', 'Hybrid', 'content', ['SP-005','SP-006'], ['IP-01'], ['FT-02','FT-03'], ['F05','F06'],
    'Define each pilot pathway learning goal, entry requirements, ordered approved variants, easier alternatives, progression conditions, next step and short parent setup guidance.',
    ['Every offered path has a start, ordered activities and next step tied to exact approved variants', 'Coverage distinguishes age suitability from ability and includes mature language for older beginners', 'Missing or withdrawn variants prevent offering the path; twelve is a pilot catalog size, not an authoring limit'],
    'Coaching lead approves actual prescriptions, sequence and supervision; content lead supplies reviewed assets and coverage.'],
  [152, 'Specify deterministic next-session rules and precedence', 'P01', 'SP-007', 'Hybrid', 'content', ['SP-151','SP-037'], ['IP-02'], ['FT-02','FT-17'], ['F03'],
    'Specify a versioned rule table using pathway, attributed ability evidence, time, equipment, space, assistance and current assignments; define adult alternatives, conflicts and offline fallback.',
    ['Approved fixtures cover no equipment, limited time, missed session, younger advanced player, older beginner and conflicting club assignments', 'Each fixture specifies one eligible action with explanation or an explicit no-recommendation reason', 'Completion alone never raises assessed ability or silently increases or combines prescribed workload'],
    'Coach and product owner approve precedence, workload boundaries, editable inputs, reassessment and offline freshness.'],
  [153, 'Specify repeatable skill-check protocols', 'P01', 'SP-007', 'Hybrid', 'content', ['SP-005','SP-151'], ['IP-03'], ['FT-18'], ['F13'],
    'Define a small coach-selected protocol set including setup, result units, valid/invalid attempts, permitted assistance, relevant conditions, retest interval and comparability.',
    ['Protocol and version identify every result; assistance, conditions and observation source are explicit', 'Coach defines comparability and invalid/no-result states without inventing age norms or talent scores', 'Recording is optional and parent observation limitations are stated'],
    'Qualified coach supplies safe protocols, retest intervals and validity/comparability decisions.'],
  [154, 'Specify the bounded coach feedback service', 'P01', 'SP-007', 'Hybrid', 'design', ['SP-037','SP-011','SP-059'], ['IP-04'], ['FT-18','FT-19','FT-25'], ['F10','F13','F21'],
    'Specify adult submission to an assigned coach, submitted/reviewed/withdrawn states, one structured cue, approved follow-up activity and no-video feedback.',
    ['Service contract names responsibility, capacity, clip limits and expected response window as approved values or explicit open decisions', 'Queue previews and playback use current grant checks; withdrawal and expiry prevent new video authorization', 'No unrestricted adult-child private chat; minimal notifications and age-appropriate next action are designed'],
    'Club/coach owner accepts workload and response expectations; safeguarding/privacy owners approve visibility and reporting.'],
  [155, 'Specify healthy weekly goals and reminder rules', 'P01', 'SP-007', 'Hybrid', 'design', ['SP-005'], ['IP-05'], ['FT-18','FT-25','FT-26'], ['F03','F11','F13'],
    'Specify optional approved weekly goals, private milestones, supportive return language, adult reminder preferences and quiet-hour behavior.',
    ['Coach/product owner define goal limits and rest/early-stop/missed-week behavior', 'Opting out keeps training access; no recording requirement, rankings, points economy or competitive minutes target', 'Earned milestones survive a break and reminder defaults/quiet hours have an explicit approved policy'],
    'Coach and product owner approve limits, copy, defaults and respectful return behavior.'],
  [156, 'Implement versioned pathway eligibility', 'P04', 'SP-019', 'Agent', 'backend', ['SP-151','SP-086'], ['IP-01'], ['FT-02','FT-16'], ['F05'],
    'Extend shared content contracts with ordered pathway steps, entry/progression rules, parent guidance and exact asset eligibility, reusing drill/plan versions.',
    ['Eligible path resolves complete approved steps; missing/withdrawn variants make it unavailable with a reason', 'Historical and active sessions keep immutable path and variant identity', 'Contract supports more than twelve drills and keeps age/ability separate'],
    'Backend and coaching leads accept SP-151 contract and migration compatibility.'],
  [157, 'Implement Today next-session recommendation rules', 'P05', 'SP-019', 'Agent', 'mobile', ['SP-152','SP-156','SP-096','SP-097','SP-115'], ['IP-02'], ['FT-02','FT-17'], ['F03'],
    'Implement the approved deterministic shared ruleset and wire one explained next activity, adult alternative and valid offline fallback into Today.',
    ['All six SP-152 fixtures match approved expected results with a stable ruleset version', 'Missing inputs/conflicting assignments return an understandable outcome without combining workloads', 'Offline fallback obeys approved freshness and eligibility; completion does not imply mastery'],
    'Coach/product lead supplies signed rule fixtures; technical lead fixes one shared rule owner for mobile/web.'],
  [158, 'Implement attributed assessment and comparability records', 'P04', 'SP-043', 'Agent', 'backend', ['SP-153','SP-086','SP-088'], ['IP-03'], ['FT-18'], ['F13'],
    'Extend assessment records with protocol/version, result, setup, assistance, conditions, source and append-only correction history; implement comparable/not-comparable result pairs.',
    ['Matching approved conditions compare; changed protocol/conditions are flagged with a reason', 'Parent-reported and coach-observed records remain distinguishable after corrections', 'Unrecorded attempts are valid where protocol permits; denied actors cannot read/write another player result'],
    'Coach supplies comparability fixtures; backend/security reviewers accept scoped data contract.'],
  [159, 'Build personal skill-check capture and progress views', 'P05', 'SP-043', 'Agent', 'mobile', ['SP-158','SP-098','SP-116'], ['IP-03'], ['FT-18','FT-07'], ['F10','F13'],
    'Present approved skill-check setup, optional recording, attributed result entry, correction history and personal comparison with no-result and changed-condition states.',
    ['Player sees only comparable own attempts as trends and explicit warnings for changed conditions', 'Participation and assessed skill are visually distinct with observation source visible', 'No-video valid attempt can be entered/reviewed; timer completion never creates a skill result'],
    'Coach reviews protocol presentation; design reviewer accepts both themes and age-appropriate result language.'],
  [160, 'Implement scoped feedback submissions and queue access', 'P06', 'SP-044', 'Agent', 'backend', ['SP-154','SP-104','SP-108','SP-112'], ['IP-04'], ['FT-18','FT-19','FT-20'], ['F10','F21'],
    'Implement adult submission, scoped coach queue metadata, review and withdrawal state transitions using current assigned-coach authority and exact media grants.',
    ['Duplicate submission/review/withdraw events converge; submitted, reviewed and withdrawn state is attributable', 'Unassigned/revoked coach and unrelated family cannot access queue previews, counts that disclose private submissions, or playback', 'Withdrawal/expiry prevents new video access; text-only assigned-practice feedback remains possible'],
    'Safeguarding/privacy reviewers accept SP-154 and residual link limits before implementation acceptance.'],
  [161, 'Build coach review queue and actionable player feedback', 'P06', 'SP-043', 'Agent', 'web', ['SP-160','SP-116','SP-117','SP-096','SP-119'], ['IP-04'], ['FT-18','FT-25'], ['F10','F13','F21'],
    'Build adult submit/withdraw controls, coach submitted/reviewed queue, one structured improvement cue and approved follow-up activity; show player next action and minimal notification event.',
    ['A permitted submission receives one actionable cue and eligible follow-up visible in the correct player context', 'Text-only feedback works; withdrawn/expired footage shows accurate unavailable state without stale preview access', 'Queue records review duration against the service contract and offers no unrestricted chat'],
    'Coach owner validates capacity and usability; design lead coordinates web queue and mobile next-action interface.'],
  [162, 'Implement private weekly goal and milestone state', 'P04', 'SP-043', 'Agent', 'backend', ['SP-155','SP-086','SP-105'], ['IP-05'], ['FT-18','FT-11'], ['F03','F13'],
    'Implement optional per-player weekly goals and persistent private milestones from idempotent participation events, with adult control and approved time-zone/week boundaries.',
    ['Repeated offline/sync events grant a milestone once; cross-context reads/writes are denied', 'Rest/missed week preserves earned milestones; opt-out retains training access and history', 'No recording/upload or assessed-skill claim is required to credit valid practice participation'],
    'Coach/product lead approves goal limits; technical lead resolves week-boundary and correction semantics.'],
  [163, 'Build weekly goals and supportive return experience', 'P05', 'SP-020', 'Agent', 'mobile', ['SP-162','SP-096','SP-078'], ['IP-05'], ['FT-18','FT-26'], ['F03','F11','F13'],
    'Add optional weekly-goal selection, private milestone display, adult reminder preferences and supportive return-after-break states using approved limits and copy.',
    ['Rest, early stopping, missed week and opt-out preserve immediate Stop and training access', 'Previously earned milestones remain visible after a break and across synchronization', 'Both themes and appropriate age variants avoid public comparison or pressure language'],
    'Product/coaching lead accepts rendered wording and goal limits; design reviewer checks accessibility.'],
  [164, 'Implement quiet-hour-aware optional practice reminders', 'P07', 'SP-027', 'Agent', 'backend', ['SP-155','SP-162','SP-119','SP-123'], ['IP-05'], ['FT-25','FT-11'], ['F11'],
    'Process adult-configured practice reminders using existing notification/jobs services, approved week/time-zone rules, quiet hours, current preferences and idempotent delivery keys.',
    ['Opt-out, revoked recipient and quiet hours prevent inappropriate new delivery including on retry', 'Duplicate jobs/sync and daylight-saving changes do not create duplicate reminders', 'Messages reveal no private player data and missed weeks do not create pressure or erase milestones'],
    'Product/operations owner supplies approved defaults, recipients and notification delivery test environment.'],
  [165, 'Verify all five priority journeys for pilot readiness', 'P08', 'SP-070', 'Hybrid', 'quality', ['SP-156','SP-157','SP-159','SP-161','SP-163','SP-164','SP-130'], ['IP-01','IP-02','IP-03','IP-04','IP-05'], ['FT-02','FT-18','FT-19','FT-25','FT-26'], ['F03','F05','F10','F11','F13','F21'],
    'Verify the five minimum priority journeys using approved content, deterministic fixtures and both family and club roles; attach exact candidate evidence and unresolved findings.',
    ['Pathway start/sequence/next step and all six recommendation fixtures pass on the candidate', 'Comparable/non-comparable/no-video checks preserve attributed personal progress without automatic mastery', 'Feedback withdrawal/expiry protects queue previews and playback while permitted text feedback works', 'Rest/missed-week/opt-out/offline retry/quiet-hour cases preserve milestones and avoid duplicate messages', 'Coaching, safeguarding and accessibility reviewers record actual decisions; missing evidence remains open'],
    'Named coaching, safeguarding and accessibility reviewers accept applicable evidence before SP-028 pilot gate.']
];

// Existing task homes retain their original acceptance IDs; these criteria append.
const extensions = {
  'SP-005': ['IP-01','IP-03', 'Coach review supplies pathway sequence and repeatable skill-check protocols to SP-151/SP-153 with actual approved versions'],
  'SP-006': ['IP-01', 'Sample review identifies the demonstrations/captions/cues required for SP-151 pathway coverage'],
  'SP-077': ['IP-05', 'Paired designs include SP-155 optional goals, rest, missed-week, opt-out and supportive return states'],
  'SP-084': ['IP-01','IP-02','IP-03','IP-04','IP-05', 'Shared extension contracts are owned and versioned for pathways, rules, assessments, feedback and goals before their respective implementation slices'],
  'SP-086': ['IP-01','IP-02','IP-03', 'Base content/assignment/assessment schema exposes versioned extension interfaces for SP-156/SP-157/SP-158 without duplicating domain ownership'],
  'SP-096': ['IP-01','IP-02','IP-05', 'Render SP-156 eligible foundation pathway goal, prerequisites, ordered steps, easier alternative and next step with parent guidance; Today exposes interfaces for SP-157/SP-163'],
  'SP-098': ['IP-03','IP-04', 'Source review exposes authorized attempt references for optional skill checks and deliberate adult feedback submission without automatic video sharing'],
  'SP-104': ['IP-04', 'Purpose-specific grants support SP-160 submission withdrawal/expiry and never infer viewing rights from a paid coach account'],
  'SP-113': ['IP-01','IP-02', 'Plan publication preserves pathway eligibility and source precedence inputs for deterministic recommendations; it never combines home and club workloads'],
  'SP-114': ['IP-01', 'Review queue links pathway variants to actual rights, suitability, demonstrations, captions and cues; incomplete coverage cannot publish'],
  'SP-115': ['IP-02', 'Assignments expose source, conflicts and freshness to SP-157 with approved expected home/club precedence fixtures'],
  'SP-116': ['IP-03','IP-04','IP-05', 'Base progress views provide versioned interfaces for SP-158 assessment attribution, SP-161 bounded feedback and SP-162 private goals; full integration is accepted through SP-043 and SP-165'],
  'SP-117': ['IP-04', 'Adult portal exposes explicit submit/withdraw controls through SP-160 and never represents device-local footage as remotely browsable'],
  'SP-119': ['IP-04','IP-05', 'Minimal feedback events and optional SP-164 reminders use current recipient authorization and shared idempotent notification interfaces'],
  'SP-125': ['IP-01', 'Actual released pathway coverage includes every necessary variant asset and parent guidance with named coaching approval; incomplete paths stay unavailable'],
  'SP-127': ['IP-01','IP-02','IP-03','IP-04','IP-05', 'Integrated fixture bundle includes SP-165 priority journeys with rule/protocol/pathway/build versions and both family/club contexts'],
  'SP-128': ['IP-04', 'Independent review exercises submission and queue-preview authorization, withdrawal/expiry and absence of unrestricted adult-child chat'],
  'SP-130': ['IP-01','IP-05', 'Usability/accessibility evidence covers eligible learning paths and optional goal/rest/return states in both themes'],
  'SP-137': ['IP-01','IP-02', 'Family pilot records pathway comprehension, explained next-step usefulness and setup friction with denominators'],
  'SP-138': ['IP-02','IP-04', 'Club pilot measures assignment-conflict handling, actionable feedback completion and actual coach review workload against service expectations'],
  'SP-139': ['IP-03','IP-05', 'Pilot analysis separates attributed skill-check comparability from participation and measures useful return/opt-out rather than app viewing time'],
  'SP-147': ['IP-01','IP-02','IP-03','IP-04','IP-05', 'Revised estimate separately includes pathway content/review, rules, protocols, coach queue workload, goals and reminder costs; prior workbook values remain assumptions'],
  'SP-149': ['IP-01','IP-02','IP-03','IP-04','IP-05', 'Release traceability covers IP-01–IP-05 and every ACT activity without treating planned criteria as passing evidence']
};
module.exports = {newTasks, extensions};
